# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91f5fe00eeee9dbc469d07504d91965dd3fcb98a790c05846b2b5776045d8b0e1a45a03dc61443e0bfa6e712ab8b4169807f772e96fed2fe60fd1aaa87b94c73

test:
  secret_key_base: 1d5f4d2e26fe2d6f186a5f08ea1576dfab03fd495f393fc06a2a4893f0977cad4b940be7cfc0232dcf13245376d664822474a4f2391543104a647ba6c17e181d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
